version: '3'
services:
  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    networks:
      - e-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - e-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - e-network

networks:
  e-network:
    driver: bridge
